name: CI - Build app and Docker image, push to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      #Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      #Create the pyton infra
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      #Install the build
      - name: Install Python build tools
        run: |
          python -m pip install --upgarde pip
          pip install build

      #Python package build
      - name: Build Python package
        run: python -m build

      #Docker login Docker HUB
      - name: Login in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #Docker image build
      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/devops-beadando
          docker build -t $IMAGE_NAME:latest .

      #Push the docker  image into the registery
      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/devops-beadando
          docker push $IMAGE_NAME:latest